# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g typescript
      # - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      # - npm run test
      # - npm prune --production
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -j ./hellow-world-service.zip ./build/*
artifacts:
  files:
      - hellow-world-service.zip
    # - dist/**/*
    # - package.json
    # - package-lock.json
    # - node_modules/**/*